### ISSUE TITLE
Display User Labels

### ISSUE THREAD

**Issue by shellylin** [alivedise/nephthys#6]
- If the unit of current time line is below a threshold, draw a small speech bubble with "..." above that task, to indicate that this is a task with user label.
- If the current view port is zoom in enough, show the full user label below that task.
- Hover on the task shows the full message of user label inside the detail message box as well.

**Comment by shellylin** [comment]
A slightly change of how to present the User Labels:
- On each task, use a red dot to indicate a User Label which is loged at such time, for such task.

![isis mock v2](https://f.cloud.github.com/assets/2149414/2006112/0692c9f8-870b-11e3-882c-9737bf2d9392.jpg)

**Comment by alivedise** [comment]
Fixed in 0.3.0
